#cors.allowed-origins: "*"

jwt:
  secret: pet-project-secret-key
  expirationDuration: 5m

security.require-ssl: true

server:
  error.whitelabel.enabled: false
  port: 8443
  servlet.session:
    cookie:
      http-only: true
      secure: true
    timeout: ${jwt.expirationDuration}
  ssl:
    key-store-password: pettest
    key-store: classpath:pet-ssl-key.p12
    key-store-type: PKCS12

spring:
  cache.type: redis
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  redis:
    host: localhost
    port: 6379

swagger.enabled: true
