jwt:
  secret: pet-project-secret-key
  token.duration: PT5S

server:
  error.whitelabel.enabled: false
  port: 8080

spring.datasource:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE"
  username: "test"
  password: "test"

swagger.enabled: true
