#cors.allowed-origins: "*"

jwt:
  secret: pet-project-secret-key
  expirationDuration: 5m

security.require-ssl: true

server:
  error.whitelabel.enabled: false
  port: 8443
  ssl:
    key-store-password: pettest
    key-store: classpath:pet-ssl-key.p12
    key-store-type: PKCS12

spring.datasource:
  driverClassName: "org.h2.Driver"
  url: "jdbc:h2:./test;DB_CLOSE_ON_EXIT=FALSE"
  username: "test"
  password: "test"

swagger.enabled: true
